export type Category =
  | 'productivity'
  | 'developer'
  | 'ai'
  | 'student'
  | 'utilities'
  | 'design'
  | 'media'
  | 'communication';

export interface App {
  id: string;
  name: string;
  tagline: string;
  description: string;
  url: string;
  category: Category;
  iconGradient: [string, string];
  accentColor: string;
  rating: number;
  ratingCount: number;
  size: string;
  developer: string;
  developerUrl?: string;
  isOfflineReady: boolean;
  isPWA: boolean;
  isNew: boolean;
  isTrending: boolean;
  isFeatured: boolean;
  tags: string[];
}

export interface CategoryMeta {
  id: Category;
  label: string;
  description: string;
  icon: string; // Lucide icon name
  color: string;
}

export const categoryMeta: CategoryMeta[] = [
  { id: 'ai',            label: 'AI',           description: 'Powered by intelligence',  icon: 'Sparkles',     color: '#8B5CF6' },
  { id: 'productivity',  label: 'Productivity',  description: 'Get things done',          icon: 'Briefcase',    color: '#F37338' },
  { id: 'developer',     label: 'Developer',     description: 'Tools for builders',       icon: 'Code2',        color: '#10B981' },
  { id: 'design',        label: 'Design',        description: 'Create visuals',           icon: 'Palette',      color: '#EC4899' },
  { id: 'student',       label: 'Student',       description: 'Study smarter',            icon: 'GraduationCap',color: '#3B82F6' },
  { id: 'utilities',     label: 'Utilities',     description: 'Everyday tools',           icon: 'Wrench',       color: '#F59E0B' },
  { id: 'communication', label: 'Communication', description: 'Stay connected',           icon: 'MessageCircle',color: '#6366F1' },
  { id: 'media',         label: 'Media',         description: 'Audio, video & more',      icon: 'Film',         color: '#EF4444' },
];

export const apps: App[] = [
  // ── FEATURED ────────────────────────────────────────────────────────────────
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    tagline: 'Virtual whiteboard with a hand-drawn feel',
    description: 'Collaborate on diagrams in real-time with an infinite canvas that feels like paper.',
    url: 'https://excalidraw.com',
    category: 'design',
    iconGradient: ['#6D28D9', '#4F46E5'],
    accentColor: '#7C3AED',
    rating: 4.9,
    ratingCount: 12400,
    size: '< 2 MB',
    developer: 'Excalidraw Team',
    isOfflineReady: true,
    isPWA: true,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    tags: ['whiteboard', 'drawing', 'collaboration', 'diagrams', 'offline'],
  },
  {
    id: 'squoosh',
    name: 'Squoosh',
    tagline: 'Compress and compare images with zero uploads',
    description: 'Google Chrome Labs image compression tool powered by WebAssembly. Supports WebP, AVIF, JPEG XL, and more.',
    url: 'https://squoosh.app',
    category: 'utilities',
    iconGradient: ['#EC4899', '#F97316'],
    accentColor: '#DB2777',
    rating: 4.8,
    ratingCount: 8900,
    size: '< 1 MB',
    developer: 'Google Chrome Labs',
    isOfflineReady: true,
    isPWA: true,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    tags: ['image', 'compression', 'webp', 'avif', 'offline', 'tools'],
  },
  {
    id: 'photopea',
    name: 'Photopea',
    tagline: 'Professional photo editor — PSD, XD, Sketch in browser',
    description: 'Advanced online image editor supporting PSD, XD, Sketch, PDF. Near-complete Photoshop alternative that runs entirely offline.',
    url: 'https://photopea.com',
    category: 'design',
    iconGradient: ['#1D4ED8', '#1E40AF'],
    accentColor: '#2563EB',
    rating: 4.7,
    ratingCount: 31200,
    size: '< 10 MB',
    developer: 'Ivan Kutskir',
    isOfflineReady: true,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: true,
    tags: ['photo', 'editor', 'photoshop', 'psd', 'design', 'offline'],
  },

  // ── DEVELOPER ───────────────────────────────────────────────────────────────
  {
    id: 'json-hero',
    name: 'JSON Hero',
    tagline: 'Beautiful JSON viewer with search and type inference',
    description: 'Makes reading JSON easy with keyboard navigation, search, and schema inference.',
    url: 'https://jsonhero.io',
    category: 'developer',
    iconGradient: ['#059669', '#10B981'],
    accentColor: '#10B981',
    rating: 4.8,
    ratingCount: 4200,
    size: '< 1 MB',
    developer: 'JSON Hero',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    tags: ['json', 'viewer', 'developer', 'api', 'tools'],
  },
  {
    id: 'regex101',
    name: 'Regex 101',
    tagline: 'Test and debug regular expressions with live feedback',
    description: 'Comprehensive regex tester supporting PCRE2, JavaScript, Python, and Golang engines with full explanations.',
    url: 'https://regex101.com',
    category: 'developer',
    iconGradient: ['#D97706', '#F59E0B'],
    accentColor: '#F59E0B',
    rating: 4.9,
    ratingCount: 15600,
    size: '< 1 MB',
    developer: 'Regex101',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['regex', 'developer', 'testing', 'debugging', 'tools'],
  },
  {
    id: 'codesandbox',
    name: 'CodeSandbox',
    tagline: 'Instant dev environments — React, Vue, Node and more',
    description: 'Cloud development environment. Share full-stack projects in seconds. Built-in CI/CD and GitHub sync.',
    url: 'https://codesandbox.io',
    category: 'developer',
    iconGradient: ['#111827', '#374151'],
    accentColor: '#4B5563',
    rating: 4.6,
    ratingCount: 22100,
    size: '< 5 MB',
    developer: 'CodeSandbox',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['code', 'sandbox', 'react', 'vue', 'collaboration', 'cloud'],
  },
  {
    id: 'bundlephobia',
    name: 'Bundlephobia',
    tagline: 'Find the cost of any npm package before you install',
    description: 'See minified and gzipped sizes, download times, and compare package alternatives.',
    url: 'https://bundlephobia.com',
    category: 'developer',
    iconGradient: ['#4F46E5', '#6366F1'],
    accentColor: '#6366F1',
    rating: 4.7,
    ratingCount: 3400,
    size: '< 1 MB',
    developer: 'Paskal Sinha',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['npm', 'bundle', 'size', 'optimization', 'developer'],
  },
  {
    id: 'transform-tools',
    name: 'Transform',
    tagline: 'Convert between JSON, TypeScript, GraphQL, and 20+ formats',
    description: 'A collection of code transformers. Convert JSON to TypeScript interfaces, GraphQL schemas to types, SVG to React, and more.',
    url: 'https://transform.tools',
    category: 'developer',
    iconGradient: ['#0F766E', '#0D9488'],
    accentColor: '#0D9488',
    rating: 4.8,
    ratingCount: 6700,
    size: '< 2 MB',
    developer: 'Ritesh Kumar',
    isOfflineReady: true,
    isPWA: false,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    tags: ['json', 'typescript', 'graphql', 'converter', 'developer', 'offline'],
  },

  // ── AI ───────────────────────────────────────────────────────────────────────
  {
    id: 'claude',
    name: 'Claude',
    tagline: 'Anthropic\'s AI assistant — analysis, writing, and code',
    description: 'Helpful, harmless, and honest AI assistant by Anthropic. Excellent at nuanced reasoning, long-form writing, and coding tasks.',
    url: 'https://claude.ai',
    category: 'ai',
    iconGradient: ['#B45309', '#D97706'],
    accentColor: '#D97706',
    rating: 4.8,
    ratingCount: 45000,
    size: '< 2 MB',
    developer: 'Anthropic',
    developerUrl: 'https://anthropic.com',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    tags: ['ai', 'assistant', 'writing', 'coding', 'analysis', 'anthropic'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    tagline: 'AI-powered search with real sources and citations',
    description: 'Get accurate, cited answers from across the internet. Every response comes with linked sources so you can verify information.',
    url: 'https://perplexity.ai',
    category: 'ai',
    iconGradient: ['#0284C7', '#0EA5E9'],
    accentColor: '#0EA5E9',
    rating: 4.7,
    ratingCount: 28000,
    size: '< 3 MB',
    developer: 'Perplexity AI',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    tags: ['ai', 'search', 'research', 'answers', 'citations'],
  },
  {
    id: 'gamma',
    name: 'Gamma',
    tagline: 'AI-generated presentations and documents in minutes',
    description: 'Create beautiful slides, documents, and web pages with AI. No design skills needed. Export to PPT or publish as a live link.',
    url: 'https://gamma.app',
    category: 'ai',
    iconGradient: ['#7C3AED', '#8B5CF6'],
    accentColor: '#8B5CF6',
    rating: 4.6,
    ratingCount: 12000,
    size: '< 4 MB',
    developer: 'Gamma Tech',
    isOfflineReady: false,
    isPWA: false,
    isNew: true,
    isTrending: true,
    isFeatured: false,
    tags: ['ai', 'presentations', 'slides', 'documents', 'design'],
  },
  {
    id: 'napkin-ai',
    name: 'Napkin AI',
    tagline: 'Turn text into visuals and diagrams automatically',
    description: 'Paste any text and Napkin AI generates charts, diagrams, and visual explanations. Perfect for presentations and documentation.',
    url: 'https://napkin.ai',
    category: 'ai',
    iconGradient: ['#1E40AF', '#3B82F6'],
    accentColor: '#3B82F6',
    rating: 4.5,
    ratingCount: 5400,
    size: '< 2 MB',
    developer: 'Napkin AI',
    isOfflineReady: false,
    isPWA: false,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    tags: ['ai', 'diagrams', 'visuals', 'presentations', 'automation'],
  },

  // ── PRODUCTIVITY ─────────────────────────────────────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    tagline: 'Notes, databases, kanban, wikis — all in one workspace',
    description: 'All-in-one workspace where you can write, plan, collaborate, and get organized. Used by 30M+ people worldwide.',
    url: 'https://notion.so',
    category: 'productivity',
    iconGradient: ['#18181B', '#27272A'],
    accentColor: '#52525B',
    rating: 4.7,
    ratingCount: 89000,
    size: '< 5 MB',
    developer: 'Notion Labs',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['notes', 'productivity', 'collaboration', 'wiki', 'database'],
  },
  {
    id: 'linear',
    name: 'Linear',
    tagline: 'Issue tracking built for speed — keyboard-first UX',
    description: 'Streamlined project management for software teams. Sub-50ms interactions, git integrations, and a beautiful minimal interface.',
    url: 'https://linear.app',
    category: 'productivity',
    iconGradient: ['#4C1D95', '#5B21B6'],
    accentColor: '#7C3AED',
    rating: 4.9,
    ratingCount: 18000,
    size: '< 5 MB',
    developer: 'Linear',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    tags: ['project', 'management', 'issues', 'developer', 'team'],
  },
  {
    id: 'cal-com',
    name: 'Cal.com',
    tagline: 'Open-source scheduling without the back-and-forth',
    description: 'Share your availability and let people book meetings. Open-source, self-hostable, and infinitely customizable.',
    url: 'https://cal.com',
    category: 'productivity',
    iconGradient: ['#1F2937', '#374151'],
    accentColor: '#4B5563',
    rating: 4.6,
    ratingCount: 7800,
    size: '< 3 MB',
    developer: 'Cal.com Inc.',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['scheduling', 'calendar', 'meetings', 'open-source'],
  },

  // ── STUDENT ──────────────────────────────────────────────────────────────────
  {
    id: 'anki-web',
    name: 'AnkiWeb',
    tagline: 'Spaced repetition flashcards — study smarter, not harder',
    description: 'Web version of Anki, the gold-standard spaced repetition system. Sync your cards and study anywhere without installing anything.',
    url: 'https://ankiweb.net',
    category: 'student',
    iconGradient: ['#0D9488', '#0F766E'],
    accentColor: '#0D9488',
    rating: 4.5,
    ratingCount: 42000,
    size: '< 2 MB',
    developer: 'Anki',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['flashcards', 'study', 'memory', 'spaced-repetition'],
  },
  {
    id: 'wolfram-alpha',
    name: 'WolframAlpha',
    tagline: 'Computational intelligence for math, science, and facts',
    description: 'Compute answers and perform calculations on any topic — math, chemistry, history, geography, nutrition, and more.',
    url: 'https://wolframalpha.com',
    category: 'student',
    iconGradient: ['#B91C1C', '#DC2626'],
    accentColor: '#DC2626',
    rating: 4.7,
    ratingCount: 28900,
    size: '< 2 MB',
    developer: 'Wolfram Research',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['math', 'science', 'calculator', 'research', 'facts'],
  },
  {
    id: 'quizlet',
    name: 'Quizlet',
    tagline: 'AI-powered flashcards, practice tests, and expert solutions',
    description: 'Study smarter with adaptive learning tools. Create or find study sets for any subject. Used by 600M+ learners worldwide.',
    url: 'https://quizlet.com',
    category: 'student',
    iconGradient: ['#3730A3', '#4338CA'],
    accentColor: '#4F46E5',
    rating: 4.5,
    ratingCount: 67000,
    size: '< 4 MB',
    developer: 'Quizlet Inc.',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['study', 'flashcards', 'tests', 'learning', 'ai'],
  },
  {
    id: 'desmos',
    name: 'Desmos',
    tagline: 'Beautiful, free graphing calculator in your browser',
    description: 'Graph functions, plot data, evaluate equations, and explore mathematics. Works offline and is completely free.',
    url: 'https://desmos.com/calculator',
    category: 'student',
    iconGradient: ['#0369A1', '#0284C7'],
    accentColor: '#0284C7',
    rating: 4.9,
    ratingCount: 34000,
    size: '< 1 MB',
    developer: 'Desmos Studio',
    isOfflineReady: true,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['math', 'graphing', 'calculator', 'education', 'offline'],
  },

  // ── UTILITIES ────────────────────────────────────────────────────────────────
  {
    id: 'bitwarden',
    name: 'Bitwarden',
    tagline: 'Open-source password manager — trusted by millions',
    description: 'End-to-end encrypted password vault synced across all your devices. Open-source, audited, and free for personal use.',
    url: 'https://vault.bitwarden.com',
    category: 'utilities',
    iconGradient: ['#1E40AF', '#175DDC'],
    accentColor: '#1D4ED8',
    rating: 4.8,
    ratingCount: 35000,
    size: '< 3 MB',
    developer: '8bit Solutions',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['passwords', 'security', 'vault', 'open-source', 'encrypted'],
  },
  {
    id: 'wormhole',
    name: 'Wormhole',
    tagline: 'Share files end-to-end encrypted — link expires in 24 hours',
    description: 'Send files securely with end-to-end encryption. No sign-up. Links auto-expire. Up to 10 GB per transfer.',
    url: 'https://wormhole.app',
    category: 'utilities',
    iconGradient: ['#9A3412', '#C2410C'],
    accentColor: '#F97316',
    rating: 4.7,
    ratingCount: 6400,
    size: '< 1 MB',
    developer: 'Wormhole',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    tags: ['file-sharing', 'privacy', 'encrypted', 'p2p', 'transfer'],
  },
  {
    id: 'it-tools',
    name: 'IT Tools',
    tagline: '50+ developer and IT utilities in one clean interface',
    description: 'All the small tools you need: UUID generator, base64, hash, color picker, cron parser, markdown, and much more. Works offline.',
    url: 'https://it-tools.tech',
    category: 'utilities',
    iconGradient: ['#065F46', '#059669'],
    accentColor: '#10B981',
    rating: 4.9,
    ratingCount: 11200,
    size: '< 2 MB',
    developer: 'Corentin Thomasset',
    isOfflineReady: true,
    isPWA: true,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    tags: ['tools', 'developer', 'utilities', 'offline', 'uuid', 'hash'],
  },
  {
    id: 'internxt',
    name: 'Internxt Drive',
    tagline: 'End-to-end encrypted cloud storage — privacy first',
    description: 'A privacy-focused alternative to Google Drive. Files are encrypted on your device before uploading. 10 GB free.',
    url: 'https://drive.internxt.com',
    category: 'utilities',
    iconGradient: ['#1E40AF', '#2563EB'],
    accentColor: '#3B82F6',
    rating: 4.5,
    ratingCount: 8200,
    size: '< 3 MB',
    developer: 'Internxt',
    isOfflineReady: false,
    isPWA: true,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    tags: ['cloud', 'storage', 'privacy', 'encrypted', 'files'],
  },

  // ── DESIGN ───────────────────────────────────────────────────────────────────
  {
    id: 'figma',
    name: 'Figma',
    tagline: 'Collaborative UI design — the industry standard',
    description: 'Design, prototype, and hand off — all in the browser. Real-time collaboration, components, design systems, and dev mode.',
    url: 'https://figma.com',
    category: 'design',
    iconGradient: ['#7B2FBE', '#9747FF'],
    accentColor: '#A855F7',
    rating: 4.8,
    ratingCount: 102000,
    size: '< 8 MB',
    developer: 'Figma, Inc.',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['design', 'prototyping', 'collaboration', 'ui', 'ux'],
  },
  {
    id: 'canva',
    name: 'Canva',
    tagline: 'Design anything — social posts, decks, videos, and more',
    description: 'Drag-and-drop graphic design with thousands of templates. Social media, presentations, posters, and video editing in one place.',
    url: 'https://canva.com',
    category: 'design',
    iconGradient: ['#00A4B0', '#00C4CC'],
    accentColor: '#00C4CC',
    rating: 4.6,
    ratingCount: 156000,
    size: '< 10 MB',
    developer: 'Canva Pty Ltd',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['design', 'graphics', 'templates', 'social-media', 'video'],
  },
  {
    id: 'coolors',
    name: 'Coolors',
    tagline: 'Generate stunning color palettes instantly',
    description: 'The super fast color palette generator. Lock colors you love, press Space for inspiration, and export to any format.',
    url: 'https://coolors.co',
    category: 'design',
    iconGradient: ['#92400E', '#B45309'],
    accentColor: '#F59E0B',
    rating: 4.8,
    ratingCount: 24300,
    size: '< 1 MB',
    developer: 'Coolors',
    isOfflineReady: true,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['colors', 'palette', 'design', 'generator', 'offline'],
  },

  // ── COMMUNICATION ────────────────────────────────────────────────────────────
  {
    id: 'discord',
    name: 'Discord',
    tagline: 'Voice, video, and text for communities',
    description: 'The go-to communication platform for gaming, study groups, tech communities, and friend groups. Supports servers, threads, and video.',
    url: 'https://discord.com/app',
    category: 'communication',
    iconGradient: ['#4752C4', '#5865F2'],
    accentColor: '#5865F2',
    rating: 4.5,
    ratingCount: 234000,
    size: '< 10 MB',
    developer: 'Discord Inc.',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['chat', 'voice', 'video', 'community', 'gaming'],
  },
  {
    id: 'signal',
    name: 'Signal Web',
    tagline: 'Private messaging — no ads, no tracking, ever',
    description: 'Open-source, end-to-end encrypted messaging. The gold standard for private communication. No metadata collection.',
    url: 'https://signal.org/en/',
    category: 'communication',
    iconGradient: ['#1976D2', '#2196F3'],
    accentColor: '#2196F3',
    rating: 4.7,
    ratingCount: 48000,
    size: '< 3 MB',
    developer: 'Signal Foundation',
    isOfflineReady: false,
    isPWA: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['messaging', 'privacy', 'encrypted', 'open-source', 'secure'],
  },

  // ── MEDIA ────────────────────────────────────────────────────────────────────
  {
    id: 'spotify-web',
    name: 'Spotify Web',
    tagline: '100M+ songs and podcasts — no download needed',
    description: 'Listen to music and podcasts in your browser. Full Spotify experience with playlists, recommendations, and offline mode (Premium).',
    url: 'https://open.spotify.com',
    category: 'media',
    iconGradient: ['#14532D', '#15803D'],
    accentColor: '#22C55E',
    rating: 4.5,
    ratingCount: 412000,
    size: '< 5 MB',
    developer: 'Spotify AB',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['music', 'podcasts', 'streaming', 'audio'],
  },
  {
    id: 'youtube-music',
    name: 'YouTube Music',
    tagline: 'Official music streaming from YouTube',
    description: 'Stream music and music videos. Personalized recommendations, radio stations, and a huge catalog including live performances.',
    url: 'https://music.youtube.com',
    category: 'media',
    iconGradient: ['#B91C1C', '#DC2626'],
    accentColor: '#EF4444',
    rating: 4.3,
    ratingCount: 189000,
    size: '< 5 MB',
    developer: 'Google LLC',
    isOfflineReady: false,
    isPWA: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    tags: ['music', 'streaming', 'youtube', 'videos', 'audio'],
  },
];

// ── Helpers ─────────────────────────────────────────────────────────────────

export const getApp = (id: string) => apps.find(a => a.id === id);

export const getAppsByCategory = (cat: Category) =>
  apps.filter(a => a.category === cat);

export const getFeaturedApps = () => apps.filter(a => a.isFeatured);

export const getTrendingApps = () => apps.filter(a => a.isTrending);

export const getNewApps = () => apps.filter(a => a.isNew);

export const getOfflineApps = () => apps.filter(a => a.isOfflineReady);

export const getCategoryMeta = (id: Category) =>
  categoryMeta.find(c => c.id === id);

export const searchApps = (query: string) => {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return apps.filter(
    a =>
      a.name.toLowerCase().includes(q) ||
      a.tagline.toLowerCase().includes(q) ||
      a.tags.some(t => t.includes(q)) ||
      a.category.includes(q) ||
      a.developer.toLowerCase().includes(q)
  );
};

export const formatRatingCount = (n: number): string => {
  if (n >= 1000) return `${(n / 1000).toFixed(0)}K`;
  return String(n);
};
